### ISSUE TITLE
롤셋 보는 모달창 개선

### ISSUE THREAD

**Issue by zizitm-dev** [wearewolves/werewolf#235]
어떤 롤셋을 보다가 다른 롤셋으로 넘어갈 때 스크롤이 초기화되는 점을 개선해달라는 요청이 있습니다.

- 현재 보고 있는 롤셋을 스크롤의 상단이나 가운데로 위치
- 제작순/가나다순 탭과 검색창은 스크롤에 밀리지 않게 상단에 고정

이정도 보완하면 되지 싶네여

**Comment by Arepin** [comment]
N분룰 제작 후 처리하겠습니다.

**Comment by Arepin** [comment]
- 제작순/가나다순 탭과 검색창은 스크롤에 밀리지 않게 상단에 고정

처리 완료.

**Comment by Arepin** [comment]
- 현재 보고 있는 롤셋을 스크롤의 상단이나 가운데로 위치

현재 보고 있는 롤셋을 스크롤의 상단에 위치시키는 것으로 처리 완료.
