### ISSUE TITLE
subrule add

### ISSUE THREAD

**Issue by ChungkeunLee** [wearewolves/werewolf#56]
- [x] DB에 쿼리 추가 (binary)
- [x] GUI로 마을 생성시 저장
- [x] python 상에서 binary DB를 추출
- [x] PHP 상에서 binary DB 추출

**Comment by Arepin** [comment]
#163 부로 

- DB에 subRule 칼럼 추가
- 선택 GUI 제공
- PHP 상에서 데이터 추출

까지 모두 완료.

**Comment by ChungkeunLee** [comment]
완성되었습니다. 수고많으셨습니다.
