### ISSUE TITLE
텔레파시 금지룰

### ISSUE THREAD

**Issue by ChungkeunLee** [wearewolves/werewolf#57]
- [x] #56 
- [x] 텔레파시 사용 불가 (텔파 로그 미부여)
- [x] 서로간의 정체를 알려줌 (강제 텔파 로그 사용) - 비밀로그는 OK
- [x] 텔레파시 로그 명 알아내기; 그래야 텔파로 쏘기 가능

**Comment by Arepin** [comment]
텔레파시 로그명은 

텔레
tele

이 두 가지일 겁니다.

**Comment by ChungkeunLee** [comment]
@Arepin 답변 감사드립니다. 한글로 들어가서 텔레로 시도하고, 안되면 텔파로 시도하는 것으로 하겠습니다.

**Comment by ChungkeunLee** [comment]
완료.
