### ISSUE TITLE
자동 봉인 버그

### ISSUE THREAD

**Issue by ChungkeunLee** [wearewolves/werewolf#63]
봉인 제안 후, 봉인 찬성표가 많으면 자동으로 봉인되어야 함에도 불구하고, 자동으로 넘어가지 않음. 확인 필요.

17/4/23 수정
- [x] 봉인 모듈 if문 조건 버그 수정
- [x] self.useTimetable 이 3서버는 1이던데 확인 (0만 봉인 체크함)
- [x] 참조할 수 없는 GAME_STATE.SEAL 이 있던데 이부분 확인

**Comment by ChungkeunLee** [comment]
self.players를 len(self.players)로 수정.

**Comment by Arepin** [comment]
제가 변경해서 pull한 후 확인하고 merge했습니다.

**Comment by ChungkeunLee** [comment]
#65 확인해봐야합니다. 작동확인 뿐만 아니라, 로깅 확인도 필요.

**Comment by ChungkeunLee** [comment]
이거 #69 에서 리버트했고, 다시 진행해야 합니다.

**Comment by ChungkeunLee** [comment]
해결
