### ISSUE TITLE
랑습룰

### ISSUE THREAD

**Issue by epi4** [wearewolves/werewolf#79]
#56
- [x] 인랑이 2명일 때도 랑습이 가능하려면 자가습격을 가능하게 해야함
- [x] 익펜에서 외늑을 찾는데 습격을 이용하는데 랑습룰에서는 이를 무시할지(혹은 보완하는 기능을 넣을지)
- [x] 메세지를 띄워서 인랑이 외늑을 알게 함 - python 코드 이용 외늑이 비밀로그 작성 ; 포팅만 하면 됩니다. (by 닥메)
- [x] 외로운 늑대 시작시 비밀 로그 작성 (닥메)

**Comment by ChungkeunLee** [comment]
익펜에서 외늑을 찾는데 습격을 이용하는데 랑습룰에서는 이를 무시할지(혹은 보완하는 기능을 넣을지) 관련해서, 인랑 리더도 동일한 방법으로 외늑을 탐지하는 것으로 압니다.

결국 9~10인일때만 따지면 됩니다. 이 상황은 인랑 1, 외로운 늑대 1인 상황입니다.

**Comment by epi4** [comment]
1. 인랑이 외늑을 습격할 수 있게 둔다. (외늑을 찾지 못 합니다)
2. 인랑이 외늑을 습격하지 못 하게 막아둔다.(외늑은 안 그래도 투표로 꼬리끊기 당하기 쉬운데 습격까지 당하면 직업 재미가 떨어질 수 있단 점을 고려해봅니다.)
3. 랑습은 그대로 두고 인랑이 외늑을 찾을 수 있게 제 3의 방안을 마련해둔다. (메시지 창을 따로 띄운다던가)

지금으로서는 2번째 안으로 하면 어떨까 고민되네요.

**Comment by epi4** [comment]
현재 외늑을 찾게끔 제 3의 방안으로 하기로 했고 닥메님이 수고해주셨습니다!
저는 자가습격 가능한 랑습을 확인하기로!

**Comment by ChungkeunLee** [comment]
이것도 완료되었습니당
